### ISSUE TITLE
Coverage Fails because "Free" RedisCloud instance de-activated!

### ISSUE THREAD

**Issue by nelsonic** [dwyl/hapi-auth-jwt2-example#11]
Due to inactivity our "Free" RedisCloud instance has been deactivated...

![redis-labs-no-activity](https://cloud.githubusercontent.com/assets/194400/11211885/7e282aae-8d2a-11e5-9d52-1895c04a8cf4.png)

Which means Coverage is low: https://travis-ci.org/dwyl/hapi-auth-jwt2-example#L247
https://codecov.io/github/dwyl/hapi-auth-jwt2-example/index.js?ref=f49ae3969a63cfbaa2ad0c86a66efbfd5c218c52

**Comment by iteles** [comment]
😐
