### ISSUE TITLE
How to secure properly?

### ISSUE THREAD

**Issue by techguydiy** [dwyl/hapi-auth-jwt2-example#26]
So I am using your example, which has been a HUGE help. I am to the point where everything seems to be working. I am wondering if there is anyway to lockdown the token from being used by another browser to get the information. Do I need to pair with a cookie? Or a more robust session tool? I am bit new to Hapi still.

This could be a question completely outside the point of this plug-in, if it is, I apologize. Just trying to understand to all the pieces work together.

I am wondering if my issue lies in the fact that I am currently using URL parameters to send token, I tried using:

`reply.redirect('localhost:3000/account/').header("Authorization", request.headers.authorization);`

But that doesn't seem to work with the redirect. Like I said I am new, sorry if this isn't really part of this plug-in.

Thanks,
Jason

**Comment by nelsonic** [comment]
@techguydiy thank you for taking the time to ask a _question_ (_as a GitHub issue_) so we can help you get going with your _hand-crafted_ web app!
Have you had a look at https://github.com/dwyl/hapi-auth-jwt2-cookie-example which shows how to use a `cookie` to store JWTs on a client (Web Browser) and thus not have to think about sending it back in headers? (_my apologies for not linking to this example from the `hapi-auth-jwt2` repo..._) 

To answer your `question`: we let the _Web Browser_ handle the security of storing the JWT and sending it back to the server in a ***Secure Cookie*** over ***HTTPS***. 
JWT is merely a way of storing claims which can be verified by any backend. 
If you want to do more verification on the JWT the client sends you can do that in your `verifyFunc` e.g. checking the browser (_user agent_) ID and IP address  (_but remember that is only of limited value as these can easily be "spoofed" by an attacker_)

If you have time to help us _improve_ our examples with a small Pull Request, we're always grateful for contributions! (_I've invited you to join DWYL org on GitHub so you can contribute with PRs if you have time..._)

**Comment by techguydiy** [comment]
Thank you for the fast response, this was incredibly helpful. 

I noticed my biggest problem and perhaps something someone might run into. I am building each major piece of functionality as a plugin to a main api server. Thought is to plug and play server functionality based on a manifest file. Anyway, I setup test servers for each plugin, which was using separate ports, which is obviously an issue for cookies and I didn't even think about it, the headers as well. That is why headers and cookies weren't working with the redirect

Not sure if anyone will find this helpful or if this plan is even worthwhile, but I am knee deep in it now. :)

Once I get my project actually completed and I am sure I on the right path, I will see what pieces I can contribute! Again, thanks so much for the help and the lightning fast response!

**Comment by nelsonic** [comment]
@techguydiy this is not only _helpful_ it's _crucial_ that people understand!
so thanks for taking the time to update! we look forward to your PRs and please be sure to ask any further clarifying questions you have! thanks! ❤️
